services:
  app:
    build: .
    container_name: jet_academy_backend

    env_file:
      - .env

    depends_on:
      - redis

    restart: unless-stopped

    networks:
      - internal
      - traefik-proxy

    labels:
     - "traefik.enable=true"
     - "traefik.docker.network=traefik-proxy"
     - "traefik.http.routers.jar.rule=Host(`api.jaracademy.tech`)"
     - "traefik.http.routers.jar.entrypoints=websecure"
     - "traefik.http.routers.jar.tls=true"
     - "traefik.http.routers.jar.tls.certresolver=letsencrypt"
     - "traefik.http.services.jar.loadbalancer.server.port=8000"

  redis:
    image: redis:7-alpine
    container_name: jar-redis

    restart: unless-stopped

    volumes:
      - redis_data_container:/data

    networks:
      - internal

volumes:
  redis_data_container:

networks:
  internal:

  traefik-proxy:
    external: true
